quarkus.rest-client."nextbike-api".url=https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bn/en

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type
quarkus.log.category."org.eclipse.microprofile.rest.client".level=DEBUG


